// internal/context/manager.go
package context

import (
	"fmt"

	"github.com/Convallariaxhr/convallaria/internal/llm"
)

// Config configures context window management.
type Config struct {
	MaxTokens int
	Threshold float64
}

// Manager handles context window token counting and compression.
type Manager struct {
	config Config
}

func New(config Config) *Manager {
	if config.MaxTokens == 0 {
		config.MaxTokens = 64000
	}
	if config.Threshold == 0 {
		config.Threshold = 0.8
	}
	return &Manager{config: config}
}

// EstimateTokens provides a rough estimate of token count for messages.
// Uses a simple heuristic: ~4 characters per token for English text.
func (m *Manager) EstimateTokens(messages []llm.Message) int {
	total := 0
	for _, msg := range messages {
		total += len(msg.Role) / 4
		total += len(msg.Content) / 4
		for _, tc := range msg.ToolCalls {
			total += len(tc.Function.Name) / 4
			total += len(tc.Function.Arguments) / 4
		}
	}
	if total < 1 {
		total = 1
	}
	return total
}

// NeedsCompression returns true if the token count exceeds the threshold.
func (m *Manager) NeedsCompression(messages []llm.Message) bool {
	tokens := m.EstimateTokens(messages)
	limit := int(float64(m.config.MaxTokens) * m.config.Threshold)
	return tokens > limit
}

// Compress keeps the system prompt and the last N messages, replacing older messages
// with a summary placeholder. This is a simple truncation-based approach.
// For production, the summary would be generated by the LLM.
func (m *Manager) Compress(messages []llm.Message, keepLast int) []llm.Message {
	if len(messages) <= keepLast+1 {
		return messages
	}

	var result []llm.Message

	// Always keep the system prompt
	if len(messages) > 0 && messages[0].Role == "system" {
		result = append(result, messages[0])
		messages = messages[1:]
	}

	// Add a summary placeholder for truncated messages
	truncated := len(messages) - keepLast
	if truncated > 0 {
		result = append(result, llm.Message{
			Role:    "system",
			Content: fmt.Sprintf("[Earlier conversation summarized: %d messages omitted]", truncated),
		})
	}

	// Keep the last N messages
	start := len(messages) - keepLast
	if start < 0 {
		start = 0
	}
	result = append(result, messages[start:]...)

	return result
}